//@author LE-LOY

package GUI;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JButton;

public class Todo extends javax.swing.JFrame {
    static Todo todo = new Todo();
    DefaultListModel DLM = new DefaultListModel();
    DefaultListModel DoneLM = new DefaultListModel();
    
    public Todo() {
        loadDLM();
        loadDoneLM();
        initComponents();
        
        this.getContentPane().setBackground(new Color(51, 51, 55) );
        this.getRootPane().setDefaultButton(btn_add);
        
        btn_done.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scr_tasks = new javax.swing.JScrollPane();
        lst_tasks = new javax.swing.JList<>();
        txt_input = new javax.swing.JTextField();
        btn_back = new javax.swing.JButton();
        btn_add = new javax.swing.JButton();
        btn_done = new javax.swing.JButton();
        lbl_active = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        scr_tasks.setBorder(null);
        scr_tasks.setName("scr_tasks"); // NOI18N

        lst_tasks.setBackground(new java.awt.Color(53, 53, 53));
        lst_tasks.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        lst_tasks.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lst_tasks.setForeground(new java.awt.Color(255, 255, 255));
        lst_tasks.setModel(DLM);
        lst_tasks.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lst_tasks.setName("lst_tasks"); // NOI18N
        lst_tasks.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lst_tasks_onSelect(evt);
            }
        });
        scr_tasks.setViewportView(lst_tasks);

        txt_input.setForeground(new java.awt.Color(53, 53, 53));
        txt_input.setName("txt_input"); // NOI18N
        txt_input.setPreferredSize(new java.awt.Dimension(94, 23));

        btn_back.setBackground(new java.awt.Color(51, 51, 51));
        btn_back.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btn_back.setForeground(new java.awt.Color(255, 255, 255));
        btn_back.setText(" Back ");
        btn_back.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_back.setContentAreaFilled(false);
        btn_back.setMargin(new java.awt.Insets(2, 7, 2, 7));
        btn_back.setMaximumSize(new java.awt.Dimension(100, 30));
        btn_back.setMinimumSize(new java.awt.Dimension(0, 0));
        btn_back.setName("btn_back"); // NOI18N
        btn_back.setOpaque(true);
        btn_back.setPreferredSize(new java.awt.Dimension(34, 25));
        btn_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                onMousePress(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                onMouseRelease(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                onMouseExit(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                onMouseEnter(evt);
            }
        });
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_back_onClick(evt);
            }
        });

        btn_add.setBackground(new java.awt.Color(51, 51, 51));
        btn_add.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btn_add.setForeground(new java.awt.Color(255, 255, 255));
        btn_add.setText(" + ");
        btn_add.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_add.setContentAreaFilled(false);
        btn_add.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_add.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btn_add.setMaximumSize(new java.awt.Dimension(31, 24));
        btn_add.setMinimumSize(new java.awt.Dimension(23, 24));
        btn_add.setName("btn_add"); // NOI18N
        btn_add.setOpaque(true);
        btn_add.setPreferredSize(new java.awt.Dimension(23, 24));
        btn_add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                onMousePress(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                onMouseRelease(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                onMouseExit(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                onMouseEnter(evt);
            }
        });
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_add_onClick(evt);
            }
        });

        btn_done.setBackground(new java.awt.Color(51, 51, 51));
        btn_done.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btn_done.setForeground(new java.awt.Color(255, 255, 255));
        btn_done.setText(" Done ");
        btn_done.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_done.setContentAreaFilled(false);
        btn_done.setMargin(new java.awt.Insets(2, 7, 2, 7));
        btn_done.setMaximumSize(new java.awt.Dimension(100, 30));
        btn_done.setMinimumSize(new java.awt.Dimension(0, 0));
        btn_done.setName("btn_done"); // NOI18N
        btn_done.setOpaque(true);
        btn_done.setPreferredSize(new java.awt.Dimension(37, 25));
        btn_done.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_done_onClick(evt);
            }
        });

        lbl_active.setFont(new java.awt.Font("Dialog", 1, 21)); // NOI18N
        lbl_active.setForeground(new java.awt.Color(255, 255, 255));
        lbl_active.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_active.setText("Tasks:");
        lbl_active.setName("lbl_active"); // NOI18N
        lbl_active.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_activeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scr_tasks, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_done, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(lbl_active, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(0, 0, 0)
                        .addComponent(btn_back, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txt_input, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_back, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_done, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lbl_active, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(scr_tasks, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(txt_input, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btn_add, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void loadDLM(){
        DLM.clear();
        ArrayList tasks = TaskManager.tasks;
        int size = tasks.size();
        
        for (int i = 0; i < size; ++i) {
            DLM.addElement(tasks.get(i));
        }
        
        System.out.println("DLM loaded!");
    }
    
    private void loadDoneLM(){
        DoneLM.clear();
        ArrayList done = TaskManager.done;
        int size = done.size();
        
        for(int i=0; i<size; ++i){
            DoneLM.addElement(done.get(i));
        }
        
        System.out.println("DoneLM loaded!");
    }
    
    public void addTask(){
        String task = txt_input.getText();
        if(!task.isEmpty()){
            TaskManager.tasks.add(task);
            txt_input.setText("");
        }
    }
    
    
    private void btn_add_onClick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_add_onClick
        addTask();
        TaskManager.saveTasks();
        TaskManager.loadTasks();
        loadDLM();
    }//GEN-LAST:event_btn_add_onClick

    private void btn_back_onClick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_back_onClick
        Pomodoro.pomodoro.setEnabled(true);
        Pomodoro.pomodoro.firstTask();
        this.dispose();
    }//GEN-LAST:event_btn_back_onClick

    private void btn_done_onClick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_done_onClick
        int id = lst_tasks.getSelectedIndex();
        
        TaskManager.saveToDone(id);
        TaskManager.tasks.remove(id);
        
        TaskManager.saveTasks();
        TaskManager.loadTasks();
        DLM.remove(id);
        
        if(id==0)
            Pomodoro.pomodoro.doneTask(false);
    }//GEN-LAST:event_btn_done_onClick

    private void lst_tasks_onSelect(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lst_tasks_onSelect
        if(lbl_active.getText().equals("Tasks:"))
            btn_done.setEnabled(true);
    }//GEN-LAST:event_lst_tasks_onSelect

    private void lbl_activeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_activeMouseClicked
        if(lbl_active.getText().equals("Tasks:")){
            lbl_active.setText("Done:");
            
            loadDoneLM();
            lst_tasks.setModel(DoneLM);
            
            btn_done.setEnabled(false);
            btn_add.setEnabled(false);
            txt_input.setEnabled(false);
        } else {
            lbl_active.setText("Tasks:");
            
            loadDLM();
            lst_tasks.setModel(DLM);
            
            btn_add.setEnabled(true);
            txt_input.setEnabled(true);
        }
    }//GEN-LAST:event_lbl_activeMouseClicked

    private void onMouseEnter(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onMouseEnter
        JButton button = (JButton) evt.getSource();
        button.setBackground(new Color(35, 35, 40));
    }//GEN-LAST:event_onMouseEnter

    private void onMouseExit(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onMouseExit
        JButton button = (JButton) evt.getSource();
        button.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_onMouseExit

    private void onMousePress(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onMousePress
        JButton button = (JButton) evt.getSource();
        button.setBackground(new Color(15, 15, 20));
    }//GEN-LAST:event_onMousePress

    private void onMouseRelease(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onMouseRelease
        JButton button = (JButton) evt.getSource();
        button.setBackground(new Color(35, 35, 40));
    }//GEN-LAST:event_onMouseRelease

    
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Todo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Todo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Todo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Todo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        java.awt.EventQueue.invokeLater(() -> {
            todo.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_done;
    private javax.swing.JLabel lbl_active;
    private javax.swing.JList<String> lst_tasks;
    private javax.swing.JScrollPane scr_tasks;
    private javax.swing.JTextField txt_input;
    // End of variables declaration//GEN-END:variables
}
