//@author leloy

package GUI;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.DefaultListModel;

public class Todo extends javax.swing.JFrame {
    static Todo todo = new Todo();
    DefaultListModel DLM = new DefaultListModel();
    
    public Todo() {
        loadDLM();
        initComponents();
        
        this.getContentPane().setBackground(new Color(51, 51, 55) );
        this.getRootPane().setDefaultButton(btn_add);
        
        btn_done.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scr_tasks = new javax.swing.JScrollPane();
        lst_tasks = new javax.swing.JList<>();
        txt_input = new javax.swing.JTextField();
        btn_back = new javax.swing.JButton();
        btn_add = new javax.swing.JButton();
        btn_done = new javax.swing.JButton();
        lbl_active = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        scr_tasks.setBorder(null);
        scr_tasks.setName("scr_tasks"); // NOI18N

        lst_tasks.setBackground(new java.awt.Color(53, 53, 53));
        lst_tasks.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        lst_tasks.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lst_tasks.setForeground(new java.awt.Color(255, 255, 255));
        lst_tasks.setModel(DLM);
        lst_tasks.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lst_tasks.setName("lst_tasks"); // NOI18N
        lst_tasks.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lst_tasks_onSelect(evt);
            }
        });
        scr_tasks.setViewportView(lst_tasks);

        txt_input.setForeground(new java.awt.Color(53, 53, 53));
        txt_input.setName("txt_input"); // NOI18N
        txt_input.setPreferredSize(new java.awt.Dimension(94, 23));

        btn_back.setBackground(new java.awt.Color(53, 53, 53));
        btn_back.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btn_back.setForeground(new java.awt.Color(255, 255, 255));
        btn_back.setText("Back");
        btn_back.setMargin(new java.awt.Insets(2, 7, 2, 7));
        btn_back.setName("btn_back"); // NOI18N
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_back_onClick(evt);
            }
        });

        btn_add.setBackground(new java.awt.Color(53, 53, 53));
        btn_add.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btn_add.setForeground(new java.awt.Color(255, 255, 255));
        btn_add.setText("+");
        btn_add.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btn_add.setName("btn_add"); // NOI18N
        btn_add.setPreferredSize(new java.awt.Dimension(23, 23));
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_add_onClick(evt);
            }
        });

        btn_done.setBackground(new java.awt.Color(53, 53, 53));
        btn_done.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btn_done.setForeground(new java.awt.Color(255, 255, 255));
        btn_done.setText("Done");
        btn_done.setMargin(new java.awt.Insets(2, 7, 2, 7));
        btn_done.setName("btn_done"); // NOI18N
        btn_done.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_done_onClick(evt);
            }
        });

        lbl_active.setFont(new java.awt.Font("Dialog", 1, 21)); // NOI18N
        lbl_active.setForeground(new java.awt.Color(255, 255, 255));
        lbl_active.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_active.setText("Tasks:");
        lbl_active.setName("lbl_active"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scr_tasks)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_done)
                        .addGap(48, 48, 48)
                        .addComponent(lbl_active)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addComponent(btn_back))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txt_input, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_back)
                            .addComponent(btn_done)))
                    .addComponent(lbl_active, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(scr_tasks, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_input, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void loadDLM(){
        DLM.clear();
        ArrayList tasks = TaskManager.tasks;
        int size = tasks.size();
        
        for (int i = 0; i < size; ++i) {
            DLM.addElement(tasks.get(i));
        }
    }
    
    public void addTask(){
        String task = txt_input.getText();
        if(!task.isEmpty()){
            TaskManager.tasks.add(task);
            txt_input.setText("");
        }
    }
    
    
    private void btn_add_onClick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_add_onClick
        addTask();
        TaskManager.saveTasks();
        TaskManager.loadTasks();
        loadDLM();
    }//GEN-LAST:event_btn_add_onClick

    private void btn_back_onClick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_back_onClick
        Pomodoro.pomodoro.setEnabled(true);
        Pomodoro.pomodoro.firstTask();
        this.dispose();
    }//GEN-LAST:event_btn_back_onClick

    private void btn_done_onClick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_done_onClick
        int id = lst_tasks.getSelectedIndex();
        
        TaskManager.saveToDone(id);
        TaskManager.tasks.remove(id);
        
        TaskManager.saveTasks();
        TaskManager.loadTasks();
        DLM.remove(id);
        
        if(id==0)
            Pomodoro.pomodoro.doneTask(false);
    }//GEN-LAST:event_btn_done_onClick

    private void lst_tasks_onSelect(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lst_tasks_onSelect
        btn_done.setEnabled(true);
    }//GEN-LAST:event_lst_tasks_onSelect

    
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Todo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Todo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Todo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Todo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        java.awt.EventQueue.invokeLater(() -> {
            todo.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_done;
    private javax.swing.JLabel lbl_active;
    private javax.swing.JList<String> lst_tasks;
    private javax.swing.JScrollPane scr_tasks;
    private javax.swing.JTextField txt_input;
    // End of variables declaration//GEN-END:variables
}
